name: Github Project Board Assignment
on:
  issues:
    types:
      - assigned
jobs:
  issues-card-assignment:
  runs-on: ubuntu-latest
  steps:
    - uses: alex-page/github-project-automation-plus@v0.8.3
      with:
        project: Project-Test
        column: Todo
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}