name: Github Project Board Assignment
on:
  issues:
    types:
      - opened

jobs:
  issues-card-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project-url: https://github.com/orgs/testing-githubapps/projects/1
          github-token: ${{ PERSONAL_ACCESS_TOKEN }}
          labeled: bug
          label-operator: OR