name: Github Project Board Assignment
on:
  issues:
    types:
      - labeled
jobs:
  issues-card-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: ${{ secrets.PROJECTS_BOARD_URL }}
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labeled: wontfix, invalid, duplicate
          label-operator: NOT